#ifndef __WX_RS422_MASTER_SALVER_ADDR_DEF_H__
#define __WX_RS422_MASTER_SALVER_ADDR_DEF_H__   

/* RS422 I Master的从机地址定义 */
typedef enum {
    WX_RS422_MASTER_SLAVE_ADDR_NA,
    WX_RS422_MASTER_SLAVE_ADDR_XXX,
    WX_RS422_MASTER_SLAVE_ADDR_YYY,
    WX_RS422_MASTER_SLAVE_ADDR_BUTT,
} WxRs422MasterSlaveAddrDef;

#endif //__WX_RS422_MASTER_SALVER_ADDR_DEF_H__