#ifndef __WX_INCLUDE_H__
#define __WX_INCLUDE_H__
#include "wx_typedef.h"
#include "wx_debug.h"
#include "wx_failcode.h"
#include "wx_log.h"
#include "wx_cnt.h"
#include "wx_util.h"
#include "wx_id_def.h"
#include "xuartns550.h"
#include "FreeRTOS.h"
#include "queue.h"
#include "FreeRTOS.h"
#include "task.h"
#include "xscugic.h"
#include "wx_id_def.h"
#include "wx_msg_common.h"
#include "xcanps.h"
#include "xparameters.h"	/* SDK generated parameters */
#include "FreeRTOSConfig.h"
#include "xparameters_ps.h"
#include "xgpio.h"
#include "wx_cnt_norm.h"
#include "wx_cnt_excp.h"
#endif
