#ifndef __WX_CNT_EXCP_H__
#define __WX_CNT_EXCP_H__
/* excp cnt from 0  */
typedef enum {
	WX_EXCP_CNT_START, // keep this first
	WX_EXCP_UNEXPECT_MSG_TYPE,
	WX_EXCP_UNDEFINE,
	WX_EXCP_INVALID_MSG_BODY_LEN,
	WX_EXCP_CREATE_EVENT_MSG_FAIL,
	WX_EXCP_SEND_MSG_FAIL,
	WX_EXCP_TYPE_TASK_HANDLE_NULL,
	/* CAN */
	WX_EXCP_CAN_FRAME_DATA_LEN_ERR,
	WX_EXCP_CAN_SLAVE_INVALID_CTRL_CODE,
	WX_EXCP_CAN_SLAVE_RECV_ERR,
	WX_EXCP_CAN_SLAVE_INVALID_REQ_MSG_TYPE,
	WX_EXCP_CAN_SLAVE_MSG_APPLY_FAIL,
	WX_EXCP_CAN_SLAVE_MSG_SCHEDULE_FAIL,
	WX_EXCP_CAN_SLAVE_ACK_ERR,
	WX_EXCP_CAN_SLAVE_BIT_ERR,
	WX_EXCP_CAN_SLAVE_STUFF_ERR,
	WX_EXCP_CAN_SLAVE_FORM_ERR,
	WX_EXCP_CAN_SLAVE_CRC_ERR,
	WX_EXCP_CAN_SLAVE_BUS_OFF,
	WX_EXCP_CAN_SLAVE_RX_FIFO_OVERFLOW,
	WX_EXCP_CAN_SLAVE_RX_FIFO_UNDERFLOW,
	WX_EXCP_CAN_SLAVE_TX_HP_BUF_FULL,
	WX_EXCP_CAN_SLAVE_TX_FIFO_FULL,
	WX_EXCP_CAN_SLAVE_WAKE_UP,
	WX_EXCP_CAN_SLAVE_SLEEP,
	WX_EXCP_CAN_SLAVE_LOST_ARB,
	WX_EXCP_CAN_SLAVE_TX_FAIL,
	/* RS422 */
	WX_EXCP_RS422_SLAVE_RD_SEND_ADU_FAIL,
	WX_EXCP_RS422_SLAVE_WR_SEND_ADU_FAIL,
	WX_EXCP_RS422_SLAVE_SEND_ERR_ADU_FAIL,

	/* msg */
	WX_EXCP_TYPE_MSG_ROUTER_LIST_NULL,
	WX_EXCP_TYPE_MSG_NULL,
	WX_EXCP_TYPE_MSG_INVALID_RECVER,
	WX_EXCP_TYPE_MSG_ROUTER_UNREG,
	/* CORE_TASK */
	WX_EXCP_CORE_TASK_ENTRY_UNFOUND,
	/* module A */



	/* module B */
	WX_EXCP_RS422_SLAVE_RECV_DATA_TX_FINISH,
	WX_EXCP_RS422_SLAVE_RECV_DATA_LEN_ERR,
	WX_EXCP_RS422_SLAVE_RECV_DATA_CRC_ERR,
	WX_EXCP_RS422_SLAVE_SEND_DATA_FAIL,
	WX_EXCP_RS422_SLAVE_SEND_DATA_FAIL_0,
	WX_EXCP_RS422_SLAVE_UNSPT_MSG_TYPE,
	WX_EXCP_RS422_SLAVE_RECV_ADU_SHORT_LEN,
	WX_EXCP_RS422_SLAVE_DATA_READ_HANDLE_NULL,
	WX_EXCP_RS422_SLAVE_DATA_READ_ADDR_OUT_RANGE,
	WX_EXCP_RS422_SLAVE_DATA_WRITE_ADDR_OUT_RANGE,
	WX_EXCP_RS422_SLAVE_RECV_DATA_ADDR_ERR,
	WX_EXCP_RS422_SLAVE_RECV_DATA_FUNC_CODE_ERR,
	WX_EXCP_RS422_SLAVE_DATA_READ_FAIL,
	WX_EXCP_RS422_SLAVE_DATA_ENC_FAIL,
	WX_EXCP_RS422_SLAVE_DATA_WRITE_HANDLE_NULL,
	WX_EXCP_RS422_SLAVE_DATA_WRITE_HANDLE_ITEM_MISS,
	WX_EXCP_RS422_SLAVE_DATA_DEC_FAIL,
	WX_EXCP_RS422_SLAVE_DATA_WRITE_FAIL,
	WX_EXCP_RS422_SLAVE_MALLOC_MSG_FAIL,
	WX_RS422_MASTER_EXCP_CODE_WR_DATA_Y,
	WX_RS422_MASTER_EXCP_CODE_ENCODE_ADU,
	WX_EXCP_RS422_MASTER_DRIVER_ISR_SEND_BY_UART_FAIL,
	WX_EXCP_RS422_SLAVE_DRIVER_BUFF_TX_ADU_FAIL,

	/* if more please add here */
	WX_EXCP_CNT_BUTT,
} WxExcpCntDef;
UINT64 g_wxExcpCnt[WX_EXCP_CNT_BUTT];
#define wx_excp_cnt(a) g_wxExcpCnt[a]++


VOID WX_ExcpCnt_DbgShow(char *argv[], UINT32 argc);
#endif
