#ifndef WX_CNT_EXCP_H
#define WX_CNT_EXCPM_H
/* excp cnt from 0  */
typedef enum {
	WX_EXCP_CNT_START, // keep this first
	WX_EXCP_UNEXPECT_MSG_TYPE,
	WX_EXCP_UNDEFINE,
	WX_EXCP_INVALID_MSG_BODY_LEN,
	/* CAN */
	WX_EXCP_CAN_FRAME_DATA_LEN_ERR,
	WX_EXCP_CAN_SLAVE_INVALID_CTRL_CODE,
	WX_EXCP_CAN_SLAVE_INVALID_REQ_MSG_TYPE,
	WX_EXCP_RS422_SLAVE_RD_SEND_ADU_FAIL,
	WX_EXCP_RS422_SLAVE_WR_SEND_ADU_FAIL,
	WX_EXCP_RS422_SLAVE_SEND_ERR_ADU_FAIL,
	/* CORE_TASK */
	WX_EXCP_CORE_TASK_ENTRY_UNFOUND,
	
	/* module A */



	/* module B */
	WX_EXCP_RS422_SLAVE_RECV_DATA_TX_FINISH,
	WX_EXCP_RS422_SLAVE_RECV_DATA_LEN_ERR,
	WX_EXCP_RS422_SLAVE_RECV_DATA_CRC_ERR,
	WX_EXCP_RS422_SLAVE_SEND_DATA_FAIL,
	WX_EXCP_RS422_SLAVE_SEND_DATA_FAIL_0,
	WX_EXCP_RS422_SLAVE_UNSPT_MSG_TYPE,
	WX_EXCP_RS422_SLAVE_RECV_ADU_SHORT_LEN,
	WX_EXCP_RS422_SLAVE_DATA_READ_HANDLE_NULL,
	WX_EXCP_RS422_SLAVE_DATA_READ_FAIL,
	WX_EXCP_RS422_SLAVE_DATA_ENC_FAIL,
	WX_EXCP_RS422_SLAVE_DATA_WRITE_HANDLE_NULL,
	WX_EXCP_RS422_SLAVE_DATA_WRITE_HANDLE_ITEM_MISS,
	WX_EXCP_RS422_SLAVE_DATA_DEC_FAIL,
	WX_EXCP_RS422_SLAVE_DATA_WRITE_FAIL,

	/* if more please add here */
	WX_EXCP_CNT_BUTT,
} WxExcpCntDef;

#define wx_excp_cnt(a) 


VOID WX_ExcpCnt_DbgShow(VOID);
#endif
